# Generated by Django 5.2.1 on 2025-06-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='status',
            field=models.CharField(choices=[('В процессе', 'In Progress'), ('Выполнено', 'Completed')], default='В процессе', max_length=11, verbose_name='Статус'),
        ),
    ]
